export const GET_RANDOM_RECIPE = 'GET_RANDOM_RECIPE';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPE_INSRUCTION = 'GET_RECIPE_INSRUCTION';
export const GET_FAVORITE_RECIPES = 'GET_FAVORITE_RECIPES';
export const ADD_FAVORITE_RECIPES = 'ADD_FAVORITE_RECIPES';